apiVersion: v1
kind: Secret
metadata:
  name: delayed-notifier-secrets
  namespace: delayed-notifier
type: Opaque
stringData:
  DELAYED_NOTIFIER_POSTGRES_MASTER_DSN: "postgres://notifier_user:notifier_password@postgres:5432/notifier_db?sslmode=disable"
  DELAYED_NOTIFIER_RABBITMQ_PASSWORD: "notifier_password"
  DELAYED_NOTIFIER_REDIS_PASSWORD: ""
  POSTGRES_PASSWORD: "notifier_password"
  RABBITMQ_DEFAULT_PASS: "notifier_password"
